spring.application.name=AimHigh-backend


# Database configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# Server configuration
server.port=8080

# JWT configuration
app.jwt.secret-key=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION}

# Debug logging for startup diagnostics (remove in production)
spring.main.banner-mode=console
logging.level.org.springframework=DEBUG

# Google Oauth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# Frontend ch?y Live Server port 5500
app.frontend-url=http://localhost:5500

#Redis configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
